spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog.yaml
    enabled: true

logging:
  level:
    liquibase: DEBUG