spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9100
logging:
  level:
    com.mshop.app: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-}] %-5level %logger{36} - %msg%n"