spring:
  application:
    name: user-service-application

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          user-service-client:
            provider: keycloak
            client-id: ${keycloak.user-client.client-id}
            client-secret: ${keycloak.user-client.client-secret}
            authorization-grant-type: client_credentials

        provider:
          keycloak:
            issuer-uri: ${keycloak.issuer-uri}
            authorization-uri: ${keycloak.authorization_endpoint}
            token-uri: ${keycloak.token_endpoint}
            jwk-set-uri: ${keycloak.jwks_uri}

server:
  port: 9000
logging:
  level:
    com.mshop.app: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-}] %-5level %logger{36} - %msg%n"

keycloak:
  auth-server-url: http://localhost:8080
  realm: mshop
  issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  token_endpoint: ${keycloak.issuer-uri}/protocol/openid-connect/token
  authorization_endpoint: ${keycloak.issuer-uri}/protocol/openid-connect/auth
  jwks_uri: ${keycloak.issuer-uri}/protocol/openid-connect/certs
  admin-user-uri: ${keycloak.auth-server-url}/admin/realms/${keycloak.realm}/users
  user-client:
    client-id: user-client
    client-secret: TBF29FdZL9dKmiOFFIGvdJqmwf8mdsat